services:
  sausageapplication:
    image: sausageapplication
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: backend-dotnet/SausageApplication/Dockerfile
    ports:
      - 8080:80
    depends_on: 
      - postgres
    
  sausageapplication-frontend:
    image: sausageapplication-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 8081:8080
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6432:5432