services:
  sausageapplication:
    image: sausageapplication
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    build:
      context: .
      dockerfile: backend-dotnet/SausageApplication/Dockerfile
    ports:
      - 8080:80
    depends_on: 
      - postgres
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6432:5432