apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausage-report
  labels:
    app: sausage-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sausage-report
  template:
    metadata:
      labels:
        app: sausage-report
    spec:
      containers:
        - name: sausage-report
          image: gitlab.praktikum-services.ru:5050/std-023-61/sausage-store/sausage-backend-report:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          envFrom:
            - secretRef:
                name: sausage-report-secrets
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6
      imagePullSecrets:
        - name: gitlab-registry-access-secret