stages:
  - build
  - notify

build-backend:
  stage: build  
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar

telegram-notification-backend:
  stage: notify
  variables:
    ARTIFACT_URL: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-backend
    BODY_DATA: "{\"chat_id\": \"-1001898478582\", \"text\": \"App backend was built successfully by Vadim Alekseev. Artifact path ${ARTIFACT_URL}\", \"disable_notification\": true}"
  only:
    changes:
    - backend/*
  script:
    - 'echo $BODY_DATA'
    - |
      if [[ $CI_COMMIT_MESSAGE == *"send notification"* ]]; then
        curl -s -X POST -H "Content-Type: application/json" -d "$BODY_DATA" "https://api.telegram.org/${BOT_TOKEN}/sendMessage"
      fi
  needs:
    - build-backend