apiVersion: v1
kind: ConfigMap
metadata:
  name: sausage-frontend-conf
data:
  default.conf: |
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
  
      root /var/www/html;
  
      server_name _;
  
      location / {
        index  index.html;
        try_files $uri $uri/ /index.html;
      }
  
      location /api {
        proxy_pass http://sausage-backend:8080;
      }
    }