apiVersion: v1
kind: Service
metadata:
  name: sausage-backend
  labels:
    app: sausage-backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sausage-backend 